### PR TITLE
New wormflow

### PR DESCRIPTION
**Pull request by mihairaulea**

### CODE REVIEW

**Comment by gidili** [comment]
This is the right one as it will merge into master. Closing [the other one](https://github.com/openworm/org.wormsim.frontend/pull/60) pointing to master.

**Comment by gidili** [comment]
Pending: https://waffle.io/openworm/org.geppetto/cards/555b4ccacdaeae5f004296e4

**Comment by gidili** [comment]
@mihairaulea just to make sure, this is the only one I need to review and not the "finalFlow" branch?

**Comment by mihairaulea** [comment]
@gidili No, review the newWormflow branch, please.

**Comment by mihairaulea** [comment]
The Application class can alter the flow, so you can test. Set the wormName to null, and you are in the worm info flow. Set the wormName to a string, and you will be in the userhome flow. Checkout the home() method from the development branch, and create a new user to see the complete flow.

**Comment by gidili** [comment]
@mihairaulea this issue is a PR on the newWormflow branch... so I think we are on the same page. Thanks for explaining how to test.

**Comment by gidili** [comment]
@mihairaulea opened a few bugs:

- https://github.com/openworm/org.wormsim.frontend/issues/67
- https://github.com/openworm/org.wormsim.frontend/issues/66
- https://github.com/openworm/org.wormsim.frontend/issues/65

Once these are fixed please do the following:

-  [ ] remove all test code (where you are logging in and setting the worm name etc)
-  [ ] put back normal flows, so that we can test all possible flows with new / existing user accounts (for example right now I can't test the logout)

**Pull request merged**
